; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\programovani\WoW Editor\Test\src\zlib\zutil.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	_z_errmsg
_BSS	SEGMENT
$SG3722	DB	01H DUP (?)
$SG3715	DB	01H DUP (?)
_BSS	ENDS
CONST	SEGMENT
_z_errmsg DD	FLAT:$SG3713
	DD	FLAT:$SG3714
	DD	FLAT:$SG3715
	DD	FLAT:$SG3716
	DD	FLAT:$SG3717
	DD	FLAT:$SG3718
	DD	FLAT:$SG3719
	DD	FLAT:$SG3720
	DD	FLAT:$SG3721
	DD	FLAT:$SG3722
CONST	ENDS
_DATA	SEGMENT
$SG3713	DB	'need dictionary', 00H
$SG3714	DB	'stream end', 00H
	ORG $+1
$SG3716	DB	'file error', 00H
	ORG $+1
$SG3717	DB	'stream error', 00H
	ORG $+3
$SG3718	DB	'data error', 00H
	ORG $+1
$SG3719	DB	'insufficient memory', 00H
$SG3720	DB	'buffer error', 00H
	ORG $+3
$SG3721	DB	'incompatible version', 00H
	ORG $+3
$SG3724	DB	'1.2.5', 00H
_DATA	ENDS
PUBLIC	_zlibVersion
; Function compile flags: /Ogtp
_TEXT	SEGMENT
_zlibVersion PROC
; File c:\programovani\wow editor\test\src\zlib\zutil.c
; Line 29
	mov	eax, OFFSET $SG3724
; Line 30
	ret	0
_zlibVersion ENDP
_TEXT	ENDS
PUBLIC	_zlibCompileFlags
; Function compile flags: /Ogtp
_TEXT	SEGMENT
_zlibCompileFlags PROC
; Line 112
	mov	eax, 85					; 00000055H
; Line 113
	ret	0
_zlibCompileFlags ENDP
_TEXT	ENDS
PUBLIC	_zError
; Function compile flags: /Ogtp
_TEXT	SEGMENT
_err$ = 8						; size = 4
_zError	PROC
; Line 135
	push	ebp
	mov	ebp, esp
; Line 136
	mov	eax, DWORD PTR _err$[ebp]
	lea	ecx, DWORD PTR [eax*4]
	mov	edx, OFFSET _z_errmsg+8
	sub	edx, ecx
	mov	eax, DWORD PTR [edx]
; Line 137
	pop	ebp
	ret	0
_zError	ENDP
_TEXT	ENDS
PUBLIC	_zcalloc
EXTRN	__imp__malloc:PROC
; Function compile flags: /Ogtp
_TEXT	SEGMENT
_opaque$ = 8						; size = 4
_items$ = 12						; size = 4
_size$ = 16						; size = 4
_zcalloc PROC
; Line 304
	push	ebp
	mov	ebp, esp
; Line 307
	mov	eax, DWORD PTR _items$[ebp]
	imul	eax, DWORD PTR _size$[ebp]
	push	eax
	call	DWORD PTR __imp__malloc
	add	esp, 4
; Line 308
	pop	ebp
	ret	0
_zcalloc ENDP
_TEXT	ENDS
PUBLIC	_zcfree
EXTRN	__imp__free:PROC
; Function compile flags: /Ogtp
_TEXT	SEGMENT
_opaque$ = 8						; size = 4
_ptr$ = 12						; size = 4
_zcfree	PROC
; Line 313
	push	ebp
	mov	ebp, esp
; Line 314
	mov	eax, DWORD PTR _ptr$[ebp]
	push	eax
	call	DWORD PTR __imp__free
	add	esp, 4
; Line 316
	pop	ebp
	ret	0
_zcfree	ENDP
_TEXT	ENDS
END
